import React from "react";
import Link from "next/link";
import { motion } from "framer-motion";

function Footer() {
  return (
    <motion.footer
      className="mt-32 py-10 bg-gradient-to-t from-white/15 to-white/5 backdrop-blur-md rounded-t-3xl shadow-inner"
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      viewport={{ once: true }}
    >
      <div className="max-w-7xl mx-auto px-6 md:px-8 flex flex-col md:flex-row justify-between items-center gap-6">
        <div>
          <span className="bg-gradient-to-r from-white to-white/90 text-black px-5 py-2 rounded-full inline-block font-medium shadow-sm">
            Created by Josh Francisco
          </span>
        </div>

        <div className="text-center md:text-right">
          <p className="text-white/80">
            Background generated by{" "}
            <Link
              href="https://deep-fold.itch.io/space-background-generator"
              className="bg-white text-black px-3 py-1 rounded-full inline-block font-medium hover:shadow-md transition-all"
              target="_blank"
            >
              Deep Fold
            </Link>
          </p>
        </div>
      </div>
    </motion.footer>
  );
}

export default Footer;
