import Image from "next/image";
import React from "react";
import { ShoppingBagIcon, HomeIcon } from "@heroicons/react/24/outline";
import Link from "next/link";

function Navbar() {
  return (
    <div className="mx-auto py-3 flex mt-8 ml-auto place-content-end space-x-2 place-items-center flex-col text-end p-5">
      <div className="ml-auto">
        <h1 className="font-bold text-md font-dm-serif-display">
          Created by Josh Francisco.
        </h1>
        <h1 className="font-bold text-md font-dm-serif-display">
          Background generated by{""}{" "}
          <Link
            href="https://deep-fold.itch.io/space-background-generator"
            className="font-bold text-[#a5bdca]"
          >
            Deep Fold
          </Link>
          .
        </h1>
        <h1 className="ml-auto text-xs text-end font-major-mono-display opacity-60">
          please don&apos;t sue me nintendo i just like kirby
        </h1>
      </div>
    </div>
  );
}

export default Navbar;
